apiVersion: v1
kind: Namespace
metadata:
  name: java-app
---
apiVersion: v1
kind: Service
metadata:
  name: responder
  namespace: java-app
spec:
  selector:
    app: responder
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081